apiVersion: apps/v1
kind: Deployment
metadata:
  name: pygoat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pygoat
  template:
    metadata:
      labels:
        app: pygoat
    spec:
      containers:
        - name: pygoat
          image: pygoat:latest
          ports:
            - containerPort: 8000
